module "dispatch" {
  source                      = "../../modules/tf-createinstance"
  ssh_public_key              = "../../datafiles/id_rsa.pub"
  subnet_id                   = "/subscriptions/${var.subscription_id}/resourceGroups/${var.tags["client"]}-RG/providers/Microsoft.Network/virtualNetworks/${var.tags["client_lc"]}-network/subnets/vnet${var.environment}"
  network_security_group_id   = "/subscriptions/${var.subscription_id}/resourceGroups/${var.tags["client"]}-RG/providers/Microsoft.Network/networkSecurityGroups/${var.tags["client_lc"]}-${var.dispatch["role"]}-nsg"
  azurename_prefix            = "${var.tags["client_lc"]}${var.environment}"
  hostname                    = "${var.tags["client_lc"]}-${var.environment}${var.dispatch["role"]}-srv"
  region                      = "${var.region}"
  serverscount                = "${var.dispatch["count"]}"
  environment                 = "${var.environment}"
  os_user                     = "${var.os_user}"
  resource_group_name         = "${var.tags["client"]}-RG"
  network_security_group_name = "${var.tags["client_lc"]}-${var.dispatch["role"]}-nsg"
  network_resource_group_name = "${var.tags["client_lc"]}-network"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
}

module "dispatch_boostrap" {
  source                      = "../../modules/tf-linux"
  user_data                   = "../../scripts/linux-common.sh"
  ssh_private_key             = "../../datafiles/id_rsa"
  pub_ips                     = "${module.dispatch.servers_pubip_address}"
  os_user                     = "${var.os_user}"
  chef_project                = "${var.chef_project}"
  serverscount                = "${var.dispatch["count"]}"
  role                        = "${var.dispatch["role"]}"
  region                      = "${var.region}"
  environment                 = "${var.environment}"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
  # chef_runlist                 = "chef-client -E ${var.environment} -o role[publish]"
  # depends_list                 = ""
}

module "lb" {
  source                      = "../../modules/tf-lb"
  azurename_prefix            = "${var.tags["client_lc"]}${var.environment}"
  hostname                    = "${var.tags["client_lc"]}-${var.environment}${var.dispatch["role"]}-srv"
  region                      = "${var.region}"
  serverscount                = "${var.dispatch["count"]}"
  environment                 = "${var.environment}"
  resource_group_name         = "${var.tags["client"]}-RG"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
  server_names                = "${module.dispatch.server_names}"
  network_security_group_id   = "${module.dispatch.servers_network_security_group_id}"
  subnet_id                   = "${module.dispatch.servers_subnet_id}"
  public_ip_address_id        = "${module.dispatch.server_pubip_id}"
  tracked_url                 = "${var.tracked_url}"
}
